# Generated by Django 5.2.7 on 2025-10-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content',
            field=models.TextField(default='hi', max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tweet'),
        ),
    ]
