# Generated by Django 5.2.7 on 2025-11-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tweet_comments_tweet_parent_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweets',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='views',
        ),
    ]
