# Generated by Django 5.2.8 on 2025-11-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tweet_image_remove_tweet_retweets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.AddField(
            model_name='tweet',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_tweets', to='main.person'),
        ),
    ]
