# Generated by Django 5.2.8 on 2025-11-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_tweet_likes_tweet_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='person',
            name='following',
        ),
        migrations.AddField(
            model_name='person',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='main.person'),
        ),
    ]
